### ISSUE TITLE
Merge Carpets

### ISSUE THREAD

**Issue by abrenneke** [abrenneke/RimWorld-BronzeAge#6]
There are like, way too many carpets. Remove some duplicates? To start with, move them to dropdowns like one of the carpets has, then go on from there.

**Comment by abrenneke** [comment]
Fix in 8270798debb9bf93f674d679ced8ca126dfcac1d

**Comment by Fizzydirt** [comment]
One time I bought a new carpet and it had a sharp glass shard in it and I cut myself on it before I saw it.  True story.
