### ISSUE TITLE
Remove storage settings from small pallet

### ISSUE THREAD

**Issue by abrenneke** [abrenneke/RimWorld-BronzeAge#93]

**Comment by Fizzydirt** [comment]
What are you talking about, I can store like four jellybeans up there?

**Comment by Fizzydirt** [comment]
Oh wait, that's soft palate.

**Comment by Fizzydirt** [comment]
Still, I can stuff a bag of gummybears under a sheet.

**Comment by abrenneke** [comment]
Fix in 505f85852404c092bdd4e674517b812eabde4133
